---
policy_selector:
  static:
    policy: ocis
policies:
  - name: ocis
    routes:
      # serve oC Web assets from the Web container
      - endpoint: /
        backend: http://web:8080
        unprotected: true
      # servce oC Web config from oCIS
      - endpoint: /config.json
        backend: http://localhost:9100
        unprotected: true

      # begin of regular oCIS proxy configuration

      # we don't need the root rule for oC Web, since we replaced it
      # with the both rules above
      # - endpoint: /
      #   backend: http://localhost:9100
      #   unprotected: true
      - endpoint: /.well-known/
        backend: http://localhost:9130
        unprotected: true
      - endpoint: /konnect/
        backend: http://localhost:9130
        unprotected: true
      - endpoint: /signin/
        backend: http://localhost:9130
        unprotected: true
      - endpoint: /archiver
        backend: http://localhost:9140
      - type: regex
        endpoint: /ocs/v[12].php/cloud/user/signing-key
        backend: http://localhost:9110
      - type: regex
        endpoint: /ocs/v[12].php/config
        backend: http://localhost:9140
        unprotected: true
      - type: regex
        endpoint: /ocs/v[12].php/apps/files_sharing/api/v1/tokeninfo/unprotected
        backend: http://localhost:9140
        unprotected: true
      - endpoint: /ocs/
        backend: http://localhost:9140
      - type: query
        endpoint: /remote.php/?preview=1
        backend: http://localhost:9115
      - method: REPORT
        endpoint: /remote.php/dav/
        backend: http://localhost:9115
      - method: REPORT
        endpoint: /remote.php/webdav
        backend: http://localhost:9115
      - type: query
        endpoint: /dav/?preview=1
        backend: http://localhost:9115
      - type: query
        endpoint: /webdav/?preview=1
        backend: http://localhost:9115
      - endpoint: /remote.php/
        service: com.owncloud.web.ocdav
      - endpoint: /dav/
        service: com.owncloud.web.ocdav
      - endpoint: /webdav/
        service: com.owncloud.web.ocdav
      - endpoint: /status
        service: com.owncloud.web.ocdav
        unprotected: true
      - endpoint: /status.php
        service: com.owncloud.web.ocdav
        unprotected: true
      - endpoint: /index.php/
        service: com.owncloud.web.ocdav
      - endpoint: /apps/
        service: com.owncloud.web.ocdav
      - endpoint: /data
        backend: http://localhost:9140
        unprotected: true
      - endpoint: /app/list
        backend: http://localhost:9140
        unprotected: true
      - endpoint: /app/
        backend: http://localhost:9140
      - endpoint: /graph/
        backend: http://localhost:9120
      - endpoint: /graph-explorer
        backend: http://localhost:9135
        unprotected: true
      - endpoint: /api/v0/settings
        backend: http://localhost:9190
      - endpoint: /settings.js
        backend: http://localhost:9190
        unprotected: true
