clients:
- id: web
  name: ownCloud web app
  application_type: web
  insecure: yes
  trusted: yes
  redirect_uris:
    - https://host.docker.internal:9100/
    - https://host.docker.internal:9200/
    - https://host.docker.internal:9100/oidc-callback.html
    - https://host.docker.internal:9200/oidc-callback.html
  origins:
    - https://host.docker.internal:9100
    - https://host.docker.internal:9200
